plugins:
  - prettier-plugin-java
overrides:
  - files: "*.java"
    options:
      printWidth: 120
      tabWidth: 4
  - files: "*.{ts,tsx,js,jsx,mjs,cjs,css,scss,md,json,html,yaml,yml}"
    options:
      printWidth: 120
      tabWidth: 2
